package com.doubleA.UniTrade.service.embeddings;

import com.doubleA.UniTrade.utils.LLMServiceUtil;
import java.io.IOException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chroma.vectorstore.ChromaVectorStore;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.util.*;
import java.util.stream.Collectors;

@Service
@Slf4j
@RequiredArgsConstructor
public class ImageSearchService {
  private final ChromaVectorStore vectorStore;
  private final LLMServiceUtil llmServiceUtil;

  // Whenever an image is uploaded or updated, create an embedding for it and save it to the
  // ChromaDB. Although productId is not needed to look for the embedding (use image id),
  // it is needed when performing image search. After performing image search,
  // product id is needed to know which product the embedding is associated with
  // to display products similar to the image provided for searching.
  public String saveEmbedding(MultipartFile image, Long productId, Long imageId) {
    try {
      // get image description generated by the LLM.
      String imageDescription = llmServiceUtil.descriptionImage(image);
      Map<String, Object> metadata = new HashMap<>();
      metadata.put("productId", productId);
      metadata.put("imageId", imageId.toString());
      metadata.put("documentId", UUID.randomUUID().toString());
      // constructs a document object for data that will be vectorised.
      // use image id as the id for the document.
      // use image description generated by the LLM to convert to a vector embedding.
      // attach productId and imageId for retrieving specific product after a similarity search,
      var doc =
          Document.builder()
              .id(imageId.toString())
              .text(imageDescription)
              .metadata(metadata)
              .build();
      // sends the document to the Chroma vector store, then vector store will take the text from
      // the document (image description), uses a configured embedding model to convert it into a
      // numerical vector.
      // Then vector store will save that vector embedding (numerical vector of image description
      // text), image description text and its associated metadata into the ChromaDB collection.
      vectorStore.doAdd(List.of(doc));
      // return image id of embedding.
      return imageId.toString();
    } catch (IOException e) {
      throw new RuntimeException("Failed to process image for embeddings.", e);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  public List<Long> searchImageSimilarity(MultipartFile queryImage) {
    try {
      // get image description generated by the LLM.
      String imageDescription = llmServiceUtil.descriptionImage(queryImage);
      SearchRequest searchRequest =
          // build the search request for querying the vector database.
          SearchRequest.builder()
              // search query is the image description text.
              .query(imageDescription)
              // top 10 most similar result after converting the query text to vector embedding.
              .topK(10)
              // Only want result above 85% similarity.
              .similarityThreshold(0.85f)
              .build();
      // the Chroma vector store finds top 10 vector embeddings which are most similar to
      // the vector embedding of the image description text provided.
      List<Document> searchResult = vectorStore.doSimilaritySearch(searchRequest);
      log.info("Search result: {}", searchResult);

      searchResult.forEach(
          doc -> {
            Double score = doc.getScore();
            Object productId = doc.getMetadata().get("productId");
            log.info("Found doc with productId: {}, similarity score: {}", productId, score);
          });

      // return a list of product Ids from the search result that are not null to display products
      // that match the image uploaded for searching.
      return searchResult.stream()
          .map(doc -> doc.getMetadata().get("productId"))
          .filter(Objects::nonNull)
          // It is safer to convert the object to String first, then only to Long to avoid errors.
          .map(Object::toString)
          .map(Long::valueOf)
          .collect(Collectors.toList());
    } catch (IOException e) {
      throw new RuntimeException("Failed to process query image.", e);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}
