package com.doubleA.UniTrade.service.chroma;

import com.doubleA.UniTrade.request.EmbeddingsDeleteRequest;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chroma.vectorstore.ChromaApi;
import org.springframework.ai.chroma.vectorstore.ChromaApi.GetEmbeddingResponse;
import org.springframework.ai.chroma.vectorstore.ChromaApi.Collection;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static org.springframework.ai.chroma.vectorstore.ChromaApi.QueryRequest.Include.all;

@Component
@Service
@RequiredArgsConstructor
@Slf4j
public class ChromaService implements IChromaService {
  private final ChromaApi chromaApi;

  @Value("default_tenant")
  private String tenantName;

  @Value("default_database")
  private String databaseName;

  @Override
  public void deleteCollection(String collectionName) {
    try {
      chromaApi.deleteCollection(tenantName, databaseName, collectionName);
    } catch (Exception e) {
      throw new RuntimeException("Failed to delete collection: " + collectionName);
    }
  }

  @Override
  // Collection refers to information of a collection containing UUID of the collection, collection
  // name, metadata of the collection.
  public List<Collection> listCollections() {
    List<Collection> collections =
        Objects.requireNonNull(chromaApi.listCollections(tenantName, databaseName)).stream()
            .toList();
    if (collections.isEmpty()) {
      throw new EntityNotFoundException("No Collection Found.");
    }
    return collections;
  }

  @Override
  // to get description of the collection so we know what the collection contains.
  public Collection getCollectionByName(String collectionName) {
    Collection collection = chromaApi.getCollection(tenantName, databaseName, collectionName);
    if (collection == null) {
      throw new EntityNotFoundException("No Collection Found for " + collectionName);
    }
    return collection;
  }

  @Override
  // Embeddings refer to a list of numbers generated by AI model which represent a collection's
  // data.
  // Similar items will have similar embeddings which allow search of similar items instead of exact
  // keyword.
  public GetEmbeddingResponse getEmbeddings(String collectionId) {
    try {
      ChromaApi.GetEmbeddingsRequest request =
          new ChromaApi.GetEmbeddingsRequest(null, null, 4, 0, all);
      // getEmbeddings retrieves the data stored in a collection.
      return chromaApi.getEmbeddings(tenantName, databaseName, collectionId, request);
    } catch (Exception e) {
      throw new RuntimeException("Failed to get embeddings: " + collectionId);
    }
  }

  @Override
  // EmbeddingsDeleteRequest contains collection name and image id to delete.
  // Because embedding is required to be generated for every image
  public void deleteEmbeddingsByCollectionId(EmbeddingsDeleteRequest request) {
    // Log image Id and collection name from EmbeddingsDeleteRequest.
    // To record the details of the embeddings about to delete.
    log.info(
        "Deleting embeddings for imageId={} in collection={}",
        request.getImageId(),
        request.getCollectionName());
    // Use collection name to find the collection then get the id of the collection.
    String collectionId = getCollectionByName(request.getCollectionName()).id();
    // Use findIdsToDelete method defined later to find the id of the embedding through
    // going to the specific collection (collectionId) and use image id to find the embedding in the
    // collection.
    List<String> idsToDelete = findIdsToDelete(collectionId, Long.valueOf(request.getImageId()));
    // record not found result.
    if (idsToDelete.isEmpty()) {
      log.warn("No embeddings found for imageId={}')", request.getImageId());
      return;
    }
    // delete from the ChromaDB.
    performDelete(collectionId, idsToDelete, Long.valueOf(request.getImageId()));
  }

  // Use fetchEmbeddingsByImageId to find the embedding using collection id and image id
  // then store it to idsToDelete to performDelete later.
  private List<String> findIdsToDelete(String collectionId, Long imageId) {
    List<String> idsToDelete = new ArrayList<>();
    var embeddingResponse = fetchEmbeddingsByImageId(collectionId, imageId.toString());
    if (embeddingResponse != null && !embeddingResponse.ids().isEmpty()) {
      // a single image can be broken into multiple embeddings for different products in 1 image,
      // so there will be same image id for different embeddings.
      idsToDelete.addAll(embeddingResponse.ids());
      log.info("Found embeddings by id: {}", embeddingResponse.ids());
    }
    return idsToDelete;
  }

  private ChromaApi.GetEmbeddingResponse fetchEmbeddingsByImageId(
      String collectionId, String imageId) {
    ChromaApi.GetEmbeddingsRequest request =
        new ChromaApi.GetEmbeddingsRequest(
            // sends a request to ChromaDB to find the embedding using image id.
            List.of(imageId),
            null, // No metadata filter
            100,
            0,
            ChromaApi.QueryRequest.Include.all);
    // put collection id to find the collection first, then only find the embedding inside the
    // collection.
    return chromaApi.getEmbeddings(tenantName, databaseName, collectionId, request);
  }

  private void performDelete(String collectionId, List<String> idsToDelete, Long imageId) {
    try {
      // construct delete request to ChromaDB containing multiple Embedding Ids to delete.
      ChromaApi.DeleteEmbeddingsRequest deleteRequest =
          new ChromaApi.DeleteEmbeddingsRequest(idsToDelete, null);
      log.info("Sending delete request: {}", deleteRequest);
      // Delete embedding with specified ids in a specific collection using delete request.
      var deleteResponse =
          chromaApi.deleteEmbeddings(tenantName, databaseName, collectionId, deleteRequest);
      log.info("Chroma delete response: {}", deleteResponse);
    } catch (Exception e) {
      log.error(
          "Failed deleting embeddings for imageId={} idsToDelete={}", imageId, idsToDelete, e);
      throw new RuntimeException(e);
    }
  }
}
