package com.doubleA.UniTrade.service.chroma;

import com.doubleA.UniTrade.request.EmbeddingsDeleteRequest;
import org.springframework.ai.chroma.vectorstore.ChromaApi;
import org.springframework.ai.chroma.vectorstore.ChromaApi.GetEmbeddingResponse;
import org.springframework.ai.chroma.vectorstore.ChromaApi.Collection;

import java.util.List;

// Chroma is a vector database for storing and searching through embeddings,
// which are unstructured data returned by AI model (text, images, audio).
public interface IChromaService {
  void deleteCollection(String collectionName);

  // Collection is similar to a table in MySQL. It stores embeddings generated by AI model.
  List<Collection> listCollections();

  Collection getCollectionByName(String collectionName);

  // Embedding = what is returned from AI Model.
  GetEmbeddingResponse getEmbeddings(String collectionName);

  void deleteEmbeddingsByCollectionId(EmbeddingsDeleteRequest request);
}
